-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at http://mozilla.org/MPL/2.0/.

TestGrammarCompilation = {}

function TestGrammarCompilation:test_new_grammar_create_c_file()
	-- Given
	os.remove("test_new_grammar_create_c_file_grammar.c")
	local grammar = function ()
		test_new_grammar_create_c_file = record{
			field("num", number(8)),
		}:apply(function (value)
			value.ok = true
		end)

		export(test_new_grammar_create_c_file)
	end

	-- When
	haka.grammar.new("test_new_grammar_create_c_file", grammar, true)

	-- Then
	local f = assert(io.open("test_new_grammar_create_c_file_grammar.c", "r"))
	local line = f:read("*line")
	assertEquals(line, "/** File automatically generated by Haka. DO NOT EDIT */")
end

function TestGrammarCompilation:test_new_grammar_create_so_module()
	-- Given
	os.remove("test_new_grammar_create_so_module_grammar.so")
	local grammar = function ()
		test_new_grammar_create_so_module = record{
			field("num", number(8)),
		}:apply(function (value)
			value.ok = true
		end)

		export(test_new_grammar_create_so_module)
	end

	-- When
	haka.grammar.new("test_new_grammar_create_so_module", grammar, true)

	-- Then
	assert(io.open("test_new_grammar_create_so_module_grammar.so", "r"))
end

function TestGrammarCompilation:test_apply_on_record()
	-- Given
	local buf = haka.vbuffer_from("\x42")
	local grammar = haka.grammar.new("test_apply_on_record", function ()
		test_apply_on_record = record{
			field("num", number(8)),
		}
		export(test_apply_on_record)
	end, true)

	-- When
	local result = grammar.test_apply_on_record:parse(buf:pos('begin'))

	assertEquals(result.num, 0x42)
end

function TestGrammarCompilation:test_apply_on_sequence()
	-- Given
	local buf = haka.vbuffer_from("\x42\x43")
	local grammar = haka.grammar.new("test_apply_on_sequence", function ()
		test_apply_on_sequence = sequence{
			number(8),
			record{
				field("num", number(8)),
			},
		}
		export(test_apply_on_sequence)
	end, true)

	-- When
	local result = grammar.test_apply_on_sequence:parse(buf:pos('begin'))

	assertEquals(result.num, 0x43)
end

function TestGrammarCompilation:test_apply_on_union()
	-- Given
	local buf = haka.vbuffer_from("\x42")
	local grammar = haka.grammar.new("test_apply_on_union", function ()
		test_apply_on_union = union{
			field("foo", number(4)),
			field("bar", number(8)),
		}
		export(test_apply_on_union)
	end, true)

	-- When
	local result = grammar.test_apply_on_union:parse(buf:pos('begin'))

	assertEquals(result.foo, 0x4)
	assertEquals(result.bar, 0x42)
end

addTestSuite('TestGrammarCompilation')
