/* File automatically generated by Haka. DO NOT EDIT */
#include <assert.h>

#include <haka/error.h>
#include <haka/log.h>
#include <haka/string_utils.h>
#include <haka/lua/lua.h>
#include <haka/lua/state.h>
#include <haka/lua/parse_ctx.h>
#include <haka/luabinding.h>

/* grammar from {{name}} */

static REGISTER_LOG_SECTION(grammar);
