.\" This Source Code Form is subject to the terms of the Mozilla Public"
.\" License, v. 2.0. If a copy of the MPL was not distributed with this"
.\" file, You can obtain one at http://mozilla.org/MPL/2.0/."
.\""
.TH HAKA 1 "2013" "Haka" Commands
.SH NAME
haka \- Launch haka daemon
.SH SYNOPSIS
\fBhaka\fP [\fIoptions\fP]
.SH DESCRIPTION
.PP 
Launch haka daemon
.SH OPTIONS
Following options are supported
.TP
\fB\-h\fP, \fB\-\-help\fP
Display help.
.TP
\fB\-\-version\fP
Display version.
.TP
\fB\-c\fP, \fB\-\-config <conf>\fP
Load a specific configuration file (default:
\fB/opt/haka/etc/haka/haka.conf\fP)
.TP
\fB\-d\fP, \fB\-\-debug\fP
Display debug output.
.TP
\fB\-\-dump-dissector-graph\fP
Dump dissector internals (grammar and state machine) in file <name>.dot.
.TP
\fB\-l\fP, \fB\-\-loglevel [<module>=]<level>[,<module>=<level>[,...]]\fP
Change haka logging level. <level> is a comma separated list of
<module>=<level>. If no module is given level will be applied globally.
.TP
\fB\-\-luadebug\fP
Attach lua debugger (and keep haka in foreground).
.TP
\fB\-\-no\-daemon\fP
Do no run in the background
.TP
\fB\-r\fP, \fB\-\-rule <file>\fP
Override the rule configuration file.
.TP
\fB\-\-opt <section>:<key>[=<value>]\fP
Override configuration parameter.
.SH FILES
\fB/var/run/haka.pid\fP records the pid of haka.
.br
\fB/var/run/haka-ctl.sock\fP is a socket used by hakactl(1).
.SH AUTHORS
Team HAKA - Arkoon
.SH COPYRIGHT
Arkoon Network Security, OpenWide and Telecom ParisTech.
