.\" This Source Code Form is subject to the terms of the Mozilla Public"
.\" License, v. 2.0. If a copy of the MPL was not distributed with this"
.\" file, You can obtain one at http://mozilla.org/MPL/2.0/."
.\""
.TH HAKAPCAP 1 "2013" "Haka" Commands
.SH NAME
hakapcap \- Use an haka config file on a pcap.
.SH SYNOPSIS
\fBhakapcap\fP [\fIoptions\fP] <\fIpcapfile\fP> <\fIconfig\fP>
.SH DESCRIPTION
.PP 
hakapcap can read a haka config file and apply it on a pcap.
.SH OPTIONS
Following options are supported.
.TP
\fB\-h\fP, \fB\-\-help\fP
Display help
.TP
\fB\-\-version\fP
Display version
.TP
\fB\-d\fP, \fB\-\-debug\fP
Display debug output
.TP
\fB\-\-luadebug\fP
Attach lua debugger
.TP
\fB\-\-pass\-through\fP
Run in pass-through mode
.TP
\fB\-o <output>\fP
Save result in a pcap file
.SH AUTHORS
Team HAKA - Arkoon
.SH COPYRIGHT
not defined yet
